export enum ChatroomsActionTypes {
  LOAD_CHATROOMS = 'LOAD_CHATROOMS',
  SELECT_CHATROOMS = 'SELECT_CHATROOMS',
  ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE',
  JOIN_CHATROOM = 'JOIN_CHATROOM'
}

export default {};
